# Generated by Django 5.1.2 on 2024-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_manager_user_player_profile_image_file_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
