# Generated by Django 5.1.2 on 2024-12-04 08:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_manager_profile_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='project.player')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='project.manager')),
            ],
        ),
    ]
